name: flutter_github_pages_test
description: Danny's Test Project
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-220.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
