name: Deploy Latest

on:
  push:
    branches:
      - main

jobs:

  sync:
    name: Rebuild Site
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: source
      - uses: actions/checkout@v2
        with:
          ref: pages
          path: destination

      - uses: DanTup/gh-actions/setup-flutter@v1.1.0
        with:
          channel: master

      - working-directory: source
        run: flutter create . --platforms web --org com.dantup --project-name flutter_app_test

      - working-directory: source
        run: flutter build web --web-renderer canvaskit --pwa-strategy none

      - working-directory: source
        run: cp -r build/web/** ../destination/

      - working-directory: destination
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add .
          git commit -m "Update site with latest" || true
          git push origin
